version: '3.8'

services:
  gateway:
    image: my-gateway-image
    container_name: gateway
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      client_net:
        ipv4_address: 192.168.10.200
      server_net:
        ipv4_address: 192.168.20.200
    tty: true
    stdin_open: true

  server1:
    image: my-server-image
    container_name: server1
    cap_add:
      - NET_ADMIN
    environment:
      - SERVER_NAME=server1
    networks:
      server_net:
        ipv4_address: 192.168.20.100

  server2:
    image: my-server-image
    container_name: server2
    cap_add:
      - NET_ADMIN
    environment:
      - SERVER_NAME=server2
    networks:
      server_net:
        ipv4_address: 192.168.20.101

  server3:
    image: my-server-image
    container_name: server3
    cap_add:
      - NET_ADMIN
    environment:
      - SERVER_NAME=server3
    networks:
      server_net:
        ipv4_address: 192.168.20.102

networks:
  client_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

  server_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
